### ISSUE TITLE
[Epic] Known List of SVG Rendering Issues

### ISSUE THREAD

**Issue by ashes999** [openfl/svg#18]
Here's a list of things that should, but don't, render correctly (or aren't supported).
- [ ] #13: background incorrectly translated
- [ ] SVGs which use `translate(x)` (but no `y`): the [SVG spec](http://www.w3.org/TR/SVG/coords.html#TransformAttribute) is `translate(x, [y = 0])`. You get a warning on build, but it appears to display correctly.
- [ ] SVGs that have a `viewBox` property on the `svg` tag, but no `width` and `height` properties, are rendered with the default size of `400x400` instead of the `viewBox` size.
- [ ] [This sun SVG icon](https://openclipart.org/detail/3367/decorative-sun-by-ivak) has a myriad of issues. Specifically, the path with `id="path9599"` (orange circle background) appears correctly in many SVG viewers (Windows, Linux) but appears mis-translated to the right and down when the icon is rendered. (You can repro this by deleting everything from the icon except the root `g` tag and this `path` tag.)
- [ ] #23: text, gradients, and rotation
- [ ] #29: dashed lines.
- [x] #31: three-character hex colours don't work
- [ ] #32: stroke width doesn't work
- [ ] #35: Stroke thickness is off by ~sqrt(2)/2
- [ ] #38: Parent/child object relationships are broken
- [ ] #41 Rotation doesn't work

**Comment by lenivaya10001** [comment]
+ rendered svg path element is always closed. The "z" syntax inside path always ignoring.
